/* Copyright (C) 2020  Ivan Pidhurskyi
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
static int g_ncodes = 130;
static char *g_codes[] = {
  [19] = "ENODEV",
  [50] = "ENOCSI",
  [113] = "EHOSTUNREACH",
  [42] = "ENOMSG",
  [117] = "EUCLEAN",
  [45] = "EL2NSYNC",
  [51] = "EL2HLT",
  [61] = "ENODATA",
  [15] = "ENOTBLK",
  [38] = "ENOSYS",
  [32] = "EPIPE",
  [22] = "EINVAL",
  [75] = "EOVERFLOW",
  [68] = "EADV",
  [4] = "EINTR",
  [87] = "EUSERS",
  [39] = "ENOTEMPTY",
  [105] = "ENOBUFS",
  [71] = "EPROTO",
  [66] = "EREMOTE",
  [119] = "ENAVAIL",
  [10] = "ECHILD",
  [40] = "ELOOP",
  [18] = "EXDEV",
  [7] = "E2BIG",
  [3] = "ESRCH",
  [90] = "EMSGSIZE",
  [97] = "EAFNOSUPPORT",
  [53] = "EBADR",
  [112] = "EHOSTDOWN",
  [96] = "EPFNOSUPPORT",
  [92] = "ENOPROTOOPT",
  [16] = "EBUSY",
  [11] = "EAGAIN",
  [77] = "EBADFD",
  [73] = "EDOTDOT",
  [106] = "EISCONN",
  [55] = "ENOANO",
  [108] = "ESHUTDOWN",
  [44] = "ECHRNG",
  [80] = "ELIBBAD",
  [64] = "ENONET",
  [52] = "EBADE",
  [9] = "EBADF",
  [72] = "EMULTIHOP",
  [5] = "EIO",
  [49] = "EUNATCH",
  [91] = "EPROTOTYPE",
  [28] = "ENOSPC",
  [8] = "ENOEXEC",
  [114] = "EALREADY",
  [100] = "ENETDOWN",
  [118] = "ENOTNAM",
  [13] = "EACCES",
  [48] = "ELNRNG",
  [84] = "EILSEQ",
  [20] = "ENOTDIR",
  [76] = "ENOTUNIQ",
  [1] = "EPERM",
  [33] = "EDOM",
  [54] = "EXFULL",
  [111] = "ECONNREFUSED",
  [21] = "EISDIR",
  [93] = "EPROTONOSUPPORT",
  [30] = "EROFS",
  [99] = "EADDRNOTAVAIL",
  [43] = "EIDRM",
  [70] = "ECOMM",
  [69] = "ESRMNT",
  [121] = "EREMOTEIO",
  [47] = "EL3RST",
  [74] = "EBADMSG",
  [23] = "ENFILE",
  [82] = "ELIBMAX",
  [29] = "ESPIPE",
  [67] = "ENOLINK",
  [102] = "ENETRESET",
  [110] = "ETIMEDOUT",
  [2] = "ENOENT",
  [17] = "EEXIST",
  [122] = "EDQUOT",
  [60] = "ENOSTR",
  [57] = "EBADSLT",
  [56] = "EBADRQC",
  [79] = "ELIBACC",
  [14] = "EFAULT",
  [27] = "EFBIG",
  [35] = "EDEADLOCK",
  [107] = "ENOTCONN",
  [89] = "EDESTADDRREQ",
  [81] = "ELIBSCN",
  [37] = "ENOLCK",
  [120] = "EISNAM",
  [103] = "ECONNABORTED",
  [101] = "ENETUNREACH",
  [116] = "ESTALE",
  [63] = "ENOSR",
  [12] = "ENOMEM",
  [88] = "ENOTSOCK",
  [86] = "ESTRPIPE",
  [31] = "EMLINK",
  [34] = "ERANGE",
  [83] = "ELIBEXEC",
  [46] = "EL3HLT",
  [104] = "ECONNRESET",
  [98] = "EADDRINUSE",
  [95] = "ENOTSUP",
  [78] = "EREMCHG",
  [36] = "ENAMETOOLONG",
  [25] = "ENOTTY",
  [85] = "ERESTART",
  [94] = "ESOCKTNOSUPPORT",
  [62] = "ETIME",
  [59] = "EBFONT",
  [109] = "ETOOMANYREFS",
  [24] = "EMFILE",
  [26] = "ETXTBSY",
  [115] = "EINPROGRESS",
  [6] = "ENXIO",
  [65] = "ENOPKG",
  [123] = "ENOMEDIUM",
  [124] = "EMEDIUMTYPE",
  [125] = "ECANCELED",
  [126] = "ENOKEY",
  [127] = "EKEYEXPIRED",
  [128] = "EKEYREVOKED",
  [129] = "EKEYREJECTED",
  [130] = "EOWNERDEAD",
  [131] = "ENOTRECOVERABLE",
  [132] = "ERFKILL",
};
